### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by joscha**
This adds Typescript typings.

### CODE REVIEW

**Comment by joscha** [comment]
When not being part of the package, this can be added as:
```ts
declare module '@psercy-io/in-percy' {
  function inPercy(): boolean;
  namespace inPercy {}
  export default inPercy;
}
```

**Comment by joscha** [comment]
Not sure why CI fails for this PR, seems to be unrelated:
```
Building storybook ...
Error:  Error: The PERCY_TOKEN environment variable is missing.
    at Object._callee$ (/home/travis/build/percy/react-percy/packages/react-percy-storybook/lib/cli.js:67:31)
    at tryCatch (/home/travis/build/percy/react-percy/packages/react-percy-storybook/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/travis/build/percy/react-percy/packages/react-percy-storybook/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/percy/react-percy/packages/react-percy-storybook/node_modules/regenerator-runtime/runtime.js:117:21)
```

**Comment by timhaines** [comment]
@joscha Thanks for this PR - and the email.  Will get back to you on both later today.

The CI build is due to Travis not setting up secret environment variables in PR's from non-repo owners - so yes, disregard that.  FWIW, it's being run as inPercy is in the same repo as react-percy-storybook, and we have integration tests that run as part of the build.

**Comment by timhaines** [comment]
Thanks @joscha!  Merged.  I'll release soon.

**Comment by timhaines** [comment]
And published.  https://github.com/percy/react-percy/releases/tag/%40percy-io%2Fin-percy%400.1.2

**Pull request merged**
