### PR TITLE
Update Interface

### PR DESCRIPTION
**Pull request by thomashuston**
*Note: this builds off of my [prettier branch](https://github.com/percy/react-percy/pull/42), see the actual diff [here](https://github.com/percy/react-percy/compare/th-prettier...interface)*

Summary
--
Updating a few aspects of the `react-percy` interface based on our conversation earlier this week.

### Suites and Snapshots

The first change is dropping the BDD-style testing `describe`/`it` lingo. We want to differentiate Percy tests from regular unit tests, so using different function names makes sense.

- `describe` => `suite`
- `it` => `snapshot`

As an example:

```jsx
import MyComponent from '../MyComponent';
import React from 'react';

suite('MyComponent', () => {

  snapshot('default', () => (
    <MyComponent />
  ));

  snapshot('selected', () => (
    <MyComponent selected />
  ));

});
```

I went with `snapshot` here as I know that's the standard term you guys use across all the other Percy integrations. I do have some concerns with that, though, given that many people will be familiar with Jest snapshots. I could easily see people getting confused by Jest-generated `__snapshots__` folders near their Percy tests, which have nothing to do with Percy.

The main alternative I see is `screenshot`, which would at least differentiate it from Jest. But I suspect you guys may have reasons you prefer the term "snapshot" to "screenshot". Open to ideas!

### Percy File Naming

This also updates `react-percy` to look for test files in `__percy__` folders or with `.percy.js`/`.percy.jsx` extensions. This mirrors the unit testing conventions of using a `__tests__` folder or `.test.js`/`.spec.js` extension.

I see some pros and cons to this naming convention.

On the plus side, it's very unambiguous that these files are related to Percy. Hopefully this will prevent people from mixing them up with unit test files.

On the other hand, if I'm a new developer jumping into a codebase and I haven't used Percy before, I might be confused by what these files are. With unit tests, I've never seen anybody create a `.jasmine.js` file or `__jest__` folder, they just use `.spec.js` and `__tests__` as those names more clearly convey *what* the files are for rather than *how* they're run. The corollary here would be to create `.screenshot.js` files or `__screenshots__` folders. As I mentioned above, "snapshots" has another meaning in many React projects, so using that naming would cause a lot of confusion (and likely break some Jest configurations).

### ESLint Plugin

With the previous `describe`/`it` naming conventions, users could easily use the `jest` or `jasmine` ESLint environment to whitelist those globals. Now that we're moving towards our own naming convention, it will be handy for users to have an easy way to whitelist the global variables we expose in Percy tests.

I've created a new package here, `eslint-plugin-react-percy`, which as of right now just contains a `globals` section that whitelists `beforeEach`, `afterEach`, `suite`, `snapshot`, etc. Note that I did not prefix the package name with `@percy-io` because ESLint has very particular rules for how it resolves plugins. The very latest versions of ESLint have gotten better about handling scoped package names, but for users with ESLint 3 it'll just cause more trouble than it's worth.

### CODE REVIEW

**Comment by fotinakis** [comment]
@thomashuston I've temporarily changed the base here from `master` to `th-prettier` to do the review. Once you've merged `th-prettier`, we can switch this back before merge.

**Comment by thomashuston** [comment]
Just merged the prettier PR. Feel free to change this back to master!

**Comment by fotinakis** [comment]
@thomashuston Done, needs a resolve merge here.

**Comment by fotinakis** [comment]
Per discussion:

### Example: flat style (default, suite name inferred from filename):

```js
// MyComponent.percy.js

percySnapshot('default', () => {
  <MyComponent />
});

percySnapshot('selected', () => {
  <MyComponent selected />
});
```

#### With beforeEach/afterEach at module level:

```js
// MyComponent.percy.js

beforeEach(() => {
  initializeCityDatabase();
});

afterEach(() => {
  clearCityDatabase();
});

percySnapshot('default', () => {
  <MyComponent />
});

percySnapshot('selected', () => {
  <MyComponent selected />
});
```

### Suite style:

```js
// MyComponent.percy.js

suite('MyComponent', () => {
  percySnapshot('default', () => {
    <MyComponent />
  });

  percySnapshot('selected', () => {
    <MyComponent selected />
  });
});
```

#### With beforeEach/afterEach in the suite:

```js
// MyComponent.percy.js

suite('MyComponent', () => {
  beforeEach(() => {
    initializeCityDatabase();
  });

  afterEach(() => {
    clearCityDatabase();
  });

  percySnapshot('default', () => {
    <MyComponent />
  });

  percySnapshot('selected', () => {
    <MyComponent selected />
  });
});
```

### Argument passing:

```js
percySnapshot('default', {widths: [375, 1280]}, () => {
  <MyComponent />
});

percySnapshot('default', {widths: [375, 1280], minimumHeight: 300, enableJavaScript: false}, () => {
  <MyComponent />
});
```

**Comment by thomashuston** [comment]
Only note I would make is that we should not support `enableJavascript` as an argument in this. The framework either needs to server-side render all test cases and upload them in the HTML already rendered, or it needs to just upload a JS file that renders the component into the page client side in Percy's rendering infra. I'd rather not have to support both systems within our code here unless there's a compelling reason, and my gut was to just switch to client rendering with JS enabled so that references to window etc. just work.

**Comment by thomashuston** [comment]
Updated `snapshot` to `percySnapshot` as we discussed. Next steps:

- Tweaking the way options are passed into suites and test cases
- Doing a round of package renames since we're talking about this supporting frameworks other than React (e.g. Vue)
    - What do we want to call this now...? The most natural name for this repo now seems like `percy-js`, but that's already used by the JS Percy client

I'd propose we merge this and tackle those two items in separate PRs, but your call!

**Pull request merged**
