### PR TITLE
Take storybook snapshots from integration tests on Travis

### PR DESCRIPTION
**Pull request by timhaines**

### CODE REVIEW

**Comment by timhaines** [comment]
@fotinakis The way I have travis configured here, it's going to run the storybook snapshots from the integration tests, and upload them to Percy.  Fab.  

It is doing them on each build though - node 4, 6, 7.  Is this preferable, as Percy's UI shows all are working consistently?  

Or would you prefer it's limited to 1 version of node?  If so, do you have a good pattern for that?  Perhaps setting PERCY_ENABLE to 0 for 2 of the versions (and adding support for PERCY_ENABLE 🍔  ).

**Comment by timhaines** [comment]
Also, I need to figure out why the CSS resources weren't uploaded in this Percy run.

**Comment by timhaines** [comment]
Well, it was cool to see the impact that fix had: https://percy.io/percy/react-percy-storybook/builds/233030

**Comment by fotinakis** [comment]
@timhaines Usually it's best to limit it to 1 version on Travis, since it's not useful to get the duplicates and also the the commit statuses may overlap in Percy in the same project. Here's how we do that in ember-percy's own tests: https://github.com/percy/ember-percy/blob/master/.travis.yml#L17

**Pull request merged**
