### PR TITLE
Upgrade babel and add transform-es2015-shorthand-properties

### PR DESCRIPTION
**Pull request by timhaines**

### CODE REVIEW

**Comment by thomashuston** [comment]
Rather than explicitly adding this plugin, we should just update our `babel-preset-env` targets to include whatever browser versions Percy needs to support. Right now we only have it configured to add plugins necessary for down to Node v4, but haven't specified any [browser versions](https://github.com/babel/babel-preset-env#targetsbrowsers).

**Comment by timhaines** [comment]
@thomashuston I thought you might know a better way of handling this.  How would you recommend setting it to cater to shorthand syntax?  

I introduced the plugin to fix this issue: https://github.com/percy/react-percy/pull/50#discussion-diff-134059037R81

**Comment by timhaines** [comment]
@thomashuston There's also some changes in that PR which update the top level react-percy project.  Feel welcome to review and comment there if there's anything you'd like to see adjusted.

**Comment by thomashuston** [comment]
Having it support the last two versions of popular browsers along with whatever specific Firefox version Percy uses should do the trick I think:

**.babelrc**
```json
{
  "presets": [
    ["env", {
      "browsers": [
        "last 2 versions",
        "Firefox >= 38"
      ],
      "node": 4
    }]
  ]
}
```

**Comment by timhaines** [comment]
@thomashuston I've added a commit removing the plugin, and [adding the browser targets](https://github.com/percy/react-percy/pull/50/commits/b88531b3885d44310e12162ff19317fb67d21fc7).  This is currently on the [per-story options pull request](https://github.com/percy/react-percy/pull/50).

Thanks for the suggestion on this one!

**Pull request merged**
